---
- name: Deploy Nginx Pod
  hosts: localhost
  become: yes
  tasks:
    - name: install pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes
        executable: pip3

    - name: Run Nginx Pod
      k8s:
        api_version: v1
        kind: Pod
        name: mynginx11
        namespace: default
        definition:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
              - name: nginx
                image: nginx
                ports:
                  - containerPort: 80



