---
- name: Deploy Nginx Pod
  hosts: localhost
  become: yes
  tasks:
    - name: install pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes
    - name: Create Nginx Pod
      kubernetes.core.k8s:
        api_version: v1
        kind: Pod
        namespace: default
        definition:
          metadata:
            name: nginx-pod
          spec:
            containers:
              - name: nginx
                image: nginx
                ports:
                  - containerPort: 80
        state: present
        wait: yes
        wait_timeout: 300
      environment:
        KUBECONFIG: /path/to/kube-config




