---
- hosts: localhost
  become_user: root
  collections:
    - kubernetes.core
  tasks:
    - name: Create a pod
      k8s:
        kubeconfig: "/home/rihab/.kube/config"
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: "nginx-pod"
            namespace: default
          spec:
            containers:
              - name: nginx-container
                image: nginx
